### PR TITLE
Update Harmonization.md

### PR DESCRIPTION
**Pull request by aaronkaplan**
adding facts

### CODE REVIEW

**Comment by larihuttunen** [comment]
Thank you for your input. If you recall our per policy from the start, which has been that we do not include the names of the persons who have contributed into this document, rather than the organizations. We see no reason to deviate from that path.

The reference to the IntelMQ data harmonization schema, however, is duly noted. It is a practical example of deriving a **schema** out of an **ontology**.

So, if you can modify your pull request to concord with the above, we see no problem of merging this into the master branch of this document.

**Comment by aaronkaplan** [comment]
On Tue, May 03, 2016 at 05:42:35AM -0700, Lari Huttunen wrote:

> Thank you for your input. If you recall our per policy from the start, which has been that we do not include the names of the persons who have contributed into this document, rather than the organizations. We see no reason to deviate from that path.

Larri, do you have any basis for this?
I do not recall this. And it is a good practice to give proper
references and credits - in science as well as industry and open source
products.

Best,
a.

> The reference to the IntelMQ data harmonization schema, however, is duly noted. It is a practical example of deriving a **schema** out of an **ontology**.
> 
> So, if you can modify your pull request to concord with the above, we see no problem of merging this into the master branch of this document.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/abusesa/abusehelper/pull/48#issuecomment-216515494

##

**Comment by larihuttunen** [comment]
@aaronkaplan 

If you review the commits, the revision history on GitHub, the predecessor on Bitbucket and the internal wikies (plural), it becomes quite evident that the policy has been this from the start.

No revision to date has put the people behind it on center stage. 

The number of people who have contributed to this document and its predecessors since 2009 is substantial.

As stated above, we welcome your input on how to make this document and its derivatives better.

As such, this is not a scientific journal or a technical standardization document. It is a community effort to help in the fight against abuse.

So let's get back to business and focus on the good fight; how to more effectively communicate indicators between organizations, shall we?

**Comment by larihuttunen** [comment]
Closing this pull request. Unbalanced highlighting of certain individuals contributions and their significance to the document is out of place.

**Pull request closed without merging**
